CREATE TABLE `ACCOUNT` (
  `ACCOUNT_ID` DECIMAL(22,0) NOT NULL,
  `LAST_NAME` VARCHAR(20) NULL DEFAULT NULL,
  `FIRST_NAME` VARCHAR(20) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(16) NULL DEFAULT NULL,
  `DATE_OF_BIRTH` DATETIME NULL DEFAULT NULL,
  `PHONE` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(20) NULL DEFAULT NULL,
  `EMERGENCY_CONTACT` VARCHAR(20) NULL DEFAULT NULL,
  `IS_ADULT` VARCHAR(5) NULL DEFAULT NULL,
  UNIQUE KEY `ACCOUNT_PK1` (`ACCOUNT_ID` ASC)
) DEFAULT CHARSET=utf8 ENGINE=InnoDB;
CREATE TABLE `TICKET` (
  `TICKET_ID` DECIMAL(22,0) NOT NULL,
  `ACCOUNT_ID` DECIMAL(22,0) NOT NULL,
  `BADGE_NAME` VARCHAR(20) NULL DEFAULT NULL,
  `PRICE` DECIMAL(22,0) NULL DEFAULT NULL,
  `EXTRAS` VARCHAR(50) NULL DEFAULT NULL,
  UNIQUE KEY `TICKET_PK` (`TICKET_ID` ASC,`ACCOUNT_ID` ASC),
  UNIQUE KEY `TICKET_PK1` (`TICKET_ID` ASC),
  CONSTRAINT `TICKET_FK_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ACCOUNT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8 ENGINE=InnoDB;
CREATE TABLE `DEPARTMENT` (
  `DEPT_ID` DECIMAL(22,0) NOT NULL,
  `NAME` VARCHAR(30) NULL DEFAULT NULL,
  `BANDANA_COLOR` VARCHAR(10) NULL DEFAULT NULL,
  UNIQUE KEY `DEPARTMENT_PK` (`DEPT_ID` ASC)
) DEFAULT CHARSET=utf8 ENGINE=InnoDB;
CREATE TABLE `HOTEL` (
  `HOTEL_ID` DECIMAL(22,0) NOT NULL,
  `NAME` VARCHAR(30) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(30) NULL DEFAULT NULL,
  `PHONE` VARCHAR(15) NULL DEFAULT NULL,
  UNIQUE KEY `HOTEL_PK` (`HOTEL_ID` ASC)
) DEFAULT CHARSET=utf8 ENGINE=InnoDB;
CREATE TABLE `HOTELROOM` (
  `HOTEL_ROOM_ID` DECIMAL(22,0) NOT NULL,
  `HOTEL_ID` DECIMAL(22,0) NULL DEFAULT NULL,
  `ROOM_NUM` DECIMAL(22,0) NULL DEFAULT NULL,
  `NUMBER_PEOPLE` DECIMAL(22,0) NULL DEFAULT NULL,
  UNIQUE KEY `HOTELROOM_PK` (`HOTEL_ROOM_ID` ASC),
  CONSTRAINT `HOTELROOM_FK_HOTEL_ID` FOREIGN KEY (`HOTEL_ID`) REFERENCES `HOTEL` (`HOTEL_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8 ENGINE=InnoDB;
CREATE TABLE `ATTENDEE` (
  `ACCOUNT_ID` DECIMAL(22,0) NULL DEFAULT NULL,
  `IS_VOLUNTEER` VARCHAR(20) NULL DEFAULT NULL,
  CONSTRAINT `ATTENDEE_FK_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ACCOUNT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8 ENGINE=InnoDB;
INSERT INTO `ACCOUNT` (`ACCOUNT_ID`,`LAST_NAME`,`FIRST_NAME`,`EMAIL`,`PASSWORD`,`DATE_OF_BIRTH`,`PHONE`,`ADDRESS`,`EMERGENCY_CONTACT`,`IS_ADULT`) VALUES (2,'Martel','Remi','remi.martel@gmail.com','123abc','1998-08-27 17:56:30','098-765-4321','321 Main St','123-456-7890','TRUE'),(3,'Laprise','Etienne','etienne.laprise@gmail.com','321abc','1998-07-15 17:58:03','321-456-7890','456 Main St','098-765-1234','TRUE'),(4,'Mercier','Guillaume','guillaume.mercier@gmail.com','321cba','1999-12-15 18:05:27','123-654-7890','654 Main St','0987-456-321','FALSE'),(1,'Fournier','William','william.fournier@gmail.com','abc123','1997-10-27 17:49:40','123-456-7890','123 Main St','098-765-4321','TRUE');
