CREATE EVENT token_cleanup
    ON SCHEDULE
      EVERY 1 HOUR
      STARTS '2017-02-20 00:00:00'
        DO
UPDATE ACCOUNT
SET PASS_TOKEN_RESET = NULL, TOKEN_EXPIRY = NULL 
WHERE TOKEN_EXPIRY < now();