CREATE EVENT token_cleanup
ON SCHEDULE
	EVERY 1 DAY_HOUR
	STARTS '2018-02-23 00:00:00'
	COMMENT 'Clean up password reset tokens every hour'
    DO 
		UPDATE ACCOUNT
		SET PASS_TOKEN_RESET = NULL, TOKEN_EXPIRY = NULL 
		WHERE TOKEN_EXPIRY < now();